FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN yarn install

COPY . .

CMD ["yarn", "start"]

#docker build -f Dockerfile.dev .
#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <container_id>
#Run Test
#docker run/exec -it <container_id> yarn test